inventry_app/urls.py
from django . urls import path
from .import views

urlpatterns = [
    path('', views.index, name="index"),
# ...........suppliier urls.........
    
    path('supplier/', views.supplier, name="supplier_mast"),
    path('supplier/edit/<int:id>/', views.edit_supplier, name='edit_supplier'),
    path('supplier/delete/<int:id>/', views.delete_supplier, name='delete_supplier'),

#....... items ........

    path('items/', views.items, name="items"),
    path('items/edit_item/<int:id>/', views.edit_item, name='edit_item'),
    path('items/delete/<int:id>/', views.delete_items, name='delete_items'),

#......Purchase............

    path('purchase/', views.purchase,name="temp_purchase"),
    path('purchase/price/', views.get_item_price,name="price"),
    path('purchase/purchase_details/', views.purchase_details,name="purchase_details"),
    
#...........sale.............

path('sale/',views.sale_mast,name="sale_mast"),
path('sale/sale-details',views.sale_details,name="sale_details"),

#...........report.............
path('purchase_report/',views.purchase_report, name="purchase_report"),
path('sale_report/',views.sale_report, name="sale_report"),
path('stock_report/',views.stock_report, name="stock_report"),


]

inventry_sys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventry_app.urls')),
]

inventry_app/models.py
import uuid
from django.db import models
from django.utils import timezone

# Create your models here.

#........... supplier..........................
class Supplier(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    contact_no = models.CharField(max_length=15)

    def __str__(self):
        return self.name




#................Items..............................
class Item(models.Model):
    item_code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    # quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    
#.......................Purchase...........................
class Purchase(models.Model):
    invoice = models.CharField(max_length=10)
    datetime = models.DateField()
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    total_amount = models.DecimalField(decimal_places=2,max_digits=10)
    
    def __str__(self):
         return self.invoice


class PurchaseDetails(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
   

class Temppurchase(models.Model):
    invoice = models.CharField(max_length=10)
    datetime = models.DateField()
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    # total_amount = models.DecimalField(decimal_places=2, max_digits=10)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    

#.......................sales..................................
class Sale(models.Model):
    customer = models.CharField(max_length=50)
    contact_no= models.CharField(max_length=11)
    invoice_no = models.CharField( max_length=10)
    datetime = models.DateField(default=timezone.now())
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    
    def generate_invoice_number(self):
        return str(uuid.uuid4().hex[:10])  # Generate a 10-character invoice number, change the length as needed

    def save(self, *args, **kwargs):
        if not self.invoice_no:
            self.invoice_no = self.generate_invoice_number()[:50]

        super(Sale, self).save(*args, **kwargs)


class SaleDetail(models.Model):
    sale =models.ForeignKey(Sale,on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.DecimalField(max_digits=10, decimal_places=2)



class Temsale(models.Model):
    customer = models.CharField(max_length=50)
    contact_no = models.CharField(max_length=11)
    invoice_no = models.CharField(max_length=50) 
    datetime = models.DateField(default=timezone.now)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
   

    

inventry_app/forms.py
from django import forms
from . models import *


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['name', 'address', 'contact_no']



class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name','item_code', 'price']
     


class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['invoice','supplier', 'datetime']
        widgets = {
            'datetime': forms.DateInput(attrs={'type': 'date', 'class': 'datepicker'}),
        }
    
    
class PurchaseDetailForm(forms.ModelForm):
    class Meta:
        model = PurchaseDetails
        fields=['item','quantity','price','amount']
    widgets = {
        'quantity': forms.NumberInput(attrs={'class': 'mr-md-4'}),
        'price': forms.NumberInput(attrs={'class': 'mr-md-4'}),
        'amount': forms.NumberInput(attrs={'class': 'mr-md-4'}),
        
        'item': forms.Select(attrs={'class': 'mr-md-4'}),
    }
    quantity = forms.IntegerField(widget=widgets['quantity'])
    price = forms.DecimalField(max_digits=10, decimal_places=2, required=False, widget=widgets['price'])
    amount = forms.DecimalField(max_digits=10, decimal_places=2, required=False, widget=widgets['amount'])
    item = forms.ModelChoiceField(queryset=Item.objects.all(), widget=widgets['item'])

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['customer','contact_no']


class SaleDetailForm(forms.ModelForm):
    class Meta:
        model= SaleDetail
        fields=['item','quantity','price','amount']

 
class PurchaseReportForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'mr-md-4 ', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'mr-md-4 ', 'type': 'date'}))


class SaleReportForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'mr-md-4 ', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'mr-md-4 ', 'type': 'date'}))

templates/dashboard/Purchase_Details.html
{% extends "partials/base.html" %}
{% block title %}purchase Details{% endblock title %}
{% block content %}
<div class="container mt-3 shadow-lg">
    <h3>Purchase Details</h3>
    <hr>
    <div class="contenar">
   
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Invoice</th>    
                    <th>Supplier</th>
                    <th>date</th>
                    <th>Details</th>
                    <th>Total Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase in data %}
                    <tr>
                        <td>{{ purchase.id }}</td>
                        <td>{{ purchase.supplier }}</td>
                        <td>{{ purchase.datetime }}</td>
                        <td>
                            <ul>
                                <li>  item   -   Quantity  -   Price - anount</li>
                                {% for purchasedetail in purchase.purchasedetails_set.all %}
                                    <li>{{ purchasedetail.item }} - {{ purchasedetail.quantity}} - {{ purchasedetail.price }} - {{ purchasedetail.amount }}</li>
                                    
                            {% endfor %}
                            </ul>
                        </td>
                        <td>{{ purchase.total_amount}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
        
    </div>
</div>
{% endblock content %}

templates/dashboard/edit_item.html
{% extends "partials/base.html" %}
{% block title %}Edit Items{% endblock title %}Edit Items
{% block content %}
<!-- Items edit -->
   <div class="container pt-2 mx-lg-5">

            <div class="form-group shadow-lg text-content-center">
                <form method="post" class=" mx-4 p-4" id="item-form" style="display: visible;">
                <h2> Edit Items</h2>
                <hr>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class=" btn btn-outline-primary form-group " 
                value="Update">
                </form>
            </div>
   
         {% comment %} <!-- Items Table -->
        <div class="col-8">
            <div class="container-fluid pt-3 shadow-lg">
                <h2>Item List</h2>
                <hr>
                <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                    <thead>
                     <tr>
                       <th class="th-sm">ID
                 
                       </th>
                       <th class="th-sm">Name
                 
                       </th>
                       <th class="th-sm">Item code
                 
                       </th>
                       <th class="th-sm">price
                 
                       </th>
                       <th class="th-sm">Quantity
                 
                       </th>
                       <th class="th-sm">Activity
                 
                       </th>
                     </tr>
                   </thead>
                   <tbody>
                       {% for i in items %}
                     <tr>
                       <td>{{i.id}}</td>
                       <td>{{i.name}}</td>
                       <td>{{i.item_code}}</td>
                       <td>{{i.price}}</td>
                       <td>{{i.quantity}}</td>
                       <td>
                           <a class="btn btn-info btn-sm" href="{% url 'edit_item' i.id %}" id="edit-btn">Edit</a>
                           <a class="btn btn-danger btn-sm" href="">Delete</a>
                       </td>
                     </tr>
                     {% endfor %}
                   </tbody>
                   {% comment %} <tfoot>
                     <tr>
                       <th>Name
                       </th>
                       <th>Position
                       </th>
                       <th>Office
                       </th>
                       <th>Age
                       </th>
                       <th>Start date
                       </th>
                       <th>Salary
                       </th>
                     </tr>
                   </tfoot>
                 </table>
            
            
            
                
               {% comment %} <div class="col-lg-6 col-md-6 shadow-lg container-fluid">
                   <table class="table bg-white table-responsive  ">
                       <h3 class="text-bold">Items List</h3>
                 
                       <thead class="bg-white">
                           <tr class="text-dark">
                               <th scope="col">Id</th>
                               <th scope="col">Name</th>
                               <th scope="col">Item code</th>
                               <th scope="col">Price</th>
                               <th scope="col">Quantity</th>
                               <th scope="col">Activity</th>
                           </tr>
                       </thead>
                       <tbody>
                           <tr>
                     {% for i in items %}
                               <th scope="row">{{i.id}}</th>
                               <td> {{i.name}}</td>
                               <td> {{i.item_code}}</td>
                               <td>{{i.price}}</td>
                               <td>{{i.quantity}}</td>
                               <td>
                                   <a class="btn btn-info btn-sm" href="{% url 'edit_item' i.id %}" id="edit-btn">Edit</a>
                                   <a class="btn btn-danger btn-sm" href="">Delete</a>
                               </td>
                           </tr>
                           {% endfor %} 
                           
                       </tbody>
                   </table>
               </div>
            </div>
               
            
    </div> {% endcomment %}
</div>  

{% endblock content %}

templates/dashboard/edit_supplier.html
{% extends "partials/base.html" %}
{% block title %} Edit Suppliers{% endblock title %}
{% block content %}

<div class="container-fruid pt-2 mx-lg-5">
    <div class="row">
        <div class="col-4">
            <div class="form-group shadow-lg">
        
                <form method="post" class="as-table mx-4 p-4" id="item-form" style="display: visible;">
                <h2> Edit Supplier</h2>
                <hr>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class=" btn btn-outline-primary form-control "
                 value="Update">
                </form>
            </div>
        </div>
    </div>
</div>  


{% endblock content %}

templates/dashboard/index.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}

<div class="container-fluid  " style="background: url('static/image/bg_image.png') ">   
    <div class="row">
        <div class="col-md-12 mb-auto" >
            
            <div class="col-md-8 offset-md-2 info">
                 <h1 class="text-center my-5 text-danger">SPPAROW</h1>
                    <h2 class="text-center text-white p-3">
                        Welcome To Our Inventry System </h2>
                        <p class="text-center text-white m-2">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, culpa? Sed in unde soluta magnam incidunt aperiam officiis nemo architecto vero! Minus natus error ducimus, 
                            ipsam accusamus provident veritatis at?consectetur adipisicing elit. Eos, culpa? Sed in unde soluta magnam incidunt aperiam officiis nemo architecto vero! Minus natus error ducimus, 
                            ipsam accusamus provident veritatis at?
                        
                        </p>
                   
                    <div class="col-md-6 offset-md-3 info my-5"><a href="{% url 'items' %}" 
                        class="btn btn-md text-center btn-danger offset-md-3 mx-6 p-3 mb-5">GET STARTED</a></div>
                </div>
            </div>
        </div> 
	</div>
    <footer class="container-fluid bg-dark text-center p-3 ">
        <small class="text-white">Copyright &copy; 2023 || Designed By Anuj kumar sahu || </small>
    </footer>
   
{% endblock content %}

templates/dashboard/items.html
{% extends "partials/base.html" %}
{% block title %}Items{% endblock title %}Items
{% block content %}

    
    <!-- Items Form -->
   <div class="container-fruid pt-2 mx-lg-5">
        <div class="row">
            <div class="col-4">
                <div class="form-group shadow-lg">
            
                    <form method="post" class="as-table mx-4 p-4" id="item-form">
                    <h2> Add Items</h2>
                    <hr>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class=" btn btn-outline-primary form-control "
                     value="Add Items">
                    </form>
                </div>
            </div>
             <!-- Items Table -->
            <div class="col-8">
                <div class="container-fluid pt-3 shadow-lg">
                    <h2>Item List</h2>
                    <hr>
                    <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                        <thead>
                         <tr>
                           <th class="th-sm">ID
                     
                           </th>
                           <th class="th-sm">Name
                     
                           </th>
                           <th class="th-sm">Item code
                     
                           </th>
                           <th class="th-sm">price
                     
                           </th>
                      
                           <th class="th-sm">Activity
                     
                           </th>
                         </tr>
                       </thead>
                       <tbody>
                           {% for i in items %}
                         <tr>
                           <td>{{i.id}}</td>
                           <td>{{i.name}}</td>
                           <td>{{i.item_code}}</td>
                           <td>{{i.price}}</td>
                           
                           <td>
                               <a class="btn btn-info btn-sm" 
                               href="{% url 'edit_item' i.id %}" id="edit-btn">Edit</a>
                               <a class="btn btn-danger btn-sm" 
                               href="{% url 'delete_items' i.id %}">Delete</a>
                           </td>
                         </tr>
                         {% endfor %}
                       </tbody>
                     </table>
                
        </div>
    </div>  



{% endblock content %}

templates/dashboard/purchase.html
{% extends "partials/base.html" %}
{% block title %}Purchase{% endblock title %}Purchase

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="container mt-3 shadow-lg">
    <h1>Purchase Management</h1>
    <hr>
    <div class="container">
            <div class="form-group">
                
                <form  method="post">
                    {% csrf_token %}
                    {{pmform.as_p}}
                    <hr>
                        {{pdform.as_table}}
                    
                <button class="btn btn-primary mb-1 d-inline" type="submit">Add Item </button>
                </form>
                <hr>
            <div>
                    <form action="" method="POST">
                        {%csrf_token%}
                        
                        <button type="submit" class="btn btn-info" 
                        name='finalSubmit' >Submit</button>
                    </form>
                </div> 
             </div>
        <div>
            <table class="table table-striped ">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Dtae and Time</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Amount</th>
                    </tr>
                </thead>
            
            <tbody>
                {% for pd in pdobj %}
                <tr>
                    <td >{{pd.item}}</td>
                    <td >{{pd.datetime}}</td>
                    <td >{{pd.quantity}}</td>
                    <td >{{pd.price}}</td>
                    <td >{{pd.amount}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        </div>     
    </div>
</div>
<script>
    var selectItem = $('#id_item');
    var quantity = $('#id_quantity');
    var price = $('#id_price');
    var amount = $('#id_amount');
    var totalAmount = $('#id_total_amount');

    $(document).ready(function() {
        $("#id_item").on("change", function() {
            var selectItem = $(this); 
            dta=selectItem.val();
            //console.log(dta)
    
            $.ajax({
                url: '/purchase/price/',
                type: 'GET',
                data: { item_id: dta }, 
                success: function(data) {
                    var myPrice = data.price;
                    //console.log(myPrice)
                    price.val(myPrice)
                    calculateAmount();
                    
                    
                },
                error: function(xhr, textStatus, errorThrown) {
                    console.error("Something went wrong! Please try again...",
                     textStatus, errorThrown);
                }

            });
        });
        function calculateAmount() {
            var quantity1 = parseFloat(quantity.val());
            var price1 = parseFloat(price.val());
           
            if (!isNaN(quantity1) && !isNaN(price1)) {
                var amount1 = quantity1 * price1;
                amount.val(amount1.toFixed(2));
            } else {
                amount.val('N/A');
            }
        }

        quantity.on("input", function() {
            calculateAmount();
        });
    });   
</script> 

{% endblock  %}

templates/dashboard/purchase_report.html
{% extends "partials/base.html" %}
{% block title %}Purchase Report{% endblock title %}
{% block content %}

        <div class="container mt-5 shadow">
            <h3 class="mt-5  mx-5">Purchase Report Date wise</h3>
            <hr>
            <form method="POST" class="as-table mx-4 p-4" id="item-form">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class=" btn btn-outline-primary  "
                 value="Search">
                </form>
            <div class="container-fluid">
                <div class="row">
          
                     <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Purchase ID</th>
                                <th>Purchase Date</th>
                                <th>Details</th>
                                <th>Total Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for purchase in pbetween %}
                                <tr>
                                    <td>{{ purchase.id }}</td>
                                    <td>{{ purchase.datetime }}</td>
                                    <td>
                                        <ul>
                                            <li>  item   -   Quantity  -   Price - anount</li>
                                            {% for purchasedetail in purchase.purchasedetails_set.all %}
                                                <li> {{ purchasedetail.item }} - {{ purchasedetail.quantity}} - {{ purchasedetail.price }} - {{ purchasedetail.amount }}</li>
                                                
                                        {% endfor %}
                                        </ul>
                                    </td>
                                    <td>{{ purchase.total_amount}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

{% endblock content %}

templates/dashboard/sale.html
{% extends "partials/base.html" %}
{% block title %}Sale{% endblock title %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="container mt-3 shadow-lg">
    <h1>Sale Management</h1>
    <hr>
    <div class="container">
        {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li class="alert alert-danger bg-danger text-white text-center" role="alert" style="list-style-type: none">{{ message }}</li>
                {% endfor %}
                </ul>
                {% endif %}
            <div class="form-group">

                <form  method="post">
                    {% csrf_token %}
                    <p class=" m-lg-2">{{smform.as_p}}</p>
                   
                    <hr> 
                        {{sdform.as_table}}
                    
                <button class="btn btn-primary mb-1 d-inline" type="submit">Add Item </button>
                </form>
                <hr>
            <div>
                    <form action="" method="POST">
                        {%csrf_token%}
                        <button type="submit" class="btn btn-info" 
                        name='finalSubmit' >Submit</button>
                    </form>
                </div> 
             </div>
        <div>
           <table class="table table-striped ">
                <thead>
                    <tr>
                        {% comment %} <th>Invoice No</th>
                        <th>Dtae and Time</th>
                        <th>Customer Name</th>
                        <th>Contact no</th> {% endcomment %}
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Amount</th>
                    </tr>
                 </thead>
                    <tbody>
                    {% for pd in tsobj %}
                    <tr>
                      <td >{{pd.item}}</td>
                        <td >{{pd.quantity}}</td>
                        <td >{{pd.price}}</td>
                        <td >{{pd.amount}}</td>
                    </tr>
                    {%endfor%}
                </tbody>
        </table> 
        </div>     
    </div>
</div>
<script>
    var selectItem = $('#id_item');
    var quantity = $('#id_quantity');
    var price = $('#id_price');
    var amount = $('#id_amount');
    var totalAmount = $('#id_total_amount');

    $(document).ready(function() {
        $("#id_item").on("change", function() {
            var selectItem = $(this); 
            dta=selectItem.val();
            console.log(dta)
    
            $.ajax({
                url: '/purchase/price/',
                type: 'GET',
                data: { item_id: dta }, 
                success: function(data) {
                    var myPrice = data.price;
                   console.log(myPrice)
                    price.val(myPrice)
                    calculateAmount();
                    
                },
                error: function(xhr, textStatus, errorThrown) {
                    console.error("Something went wrong! Please try again...",
                     textStatus, errorThrown);
                }

            });
        });
    
        // Define the calculateAmount function if needed
        function calculateAmount() {
            var quantity1 = parseFloat(quantity.val());
            var price1 = parseFloat(price.val());
           
            if (!isNaN(quantity1) && !isNaN(price1)) {
                var amount1 = quantity1 * price1;
                amount.val(amount1.toFixed(2));
   
            } else {
                // Handle invalid input (e.g., non-numeric values)
                amount.val('N/A');
            }
        }

        quantity.on("input", function() {
            calculateAmount();
        });
    });    
</script> 

{% endblock  %}

templates/dashboard/sale_details.html
{% extends "partials/base.html" %}
{% block title %}Sale Details{% endblock title %}
{% block content %}
<div class="container mt-3 shadow-lg">
    <h3>Sale Details</h3>
    <hr>
    
<table class="table table-striped">
    <thead>
        <tr>
            <th>Invoice</th> 
            <th>date</th>  
            <th>Customer</th>    
            <th>Contact no</th>
            <th>Details</th>
            
            <th>Total Amount</th>
        </tr>
    </thead>
    <tbody>
        {% for sale in data %}
            <tr>
                <td>{{ sale.invoice_no }}</td>
                <td>{{ sale.datetime }}</td>
                <td>{{ sale.customer }}</td>
                <td>{{ sale.contact_no }}</td>
                
                <td>
                    <ul>
                        <li>  item   -   Quantity  -   Price - anount</li>
                         {% for saledetail in sale.saledetail_set.all %}	
                            <li>{{ saledetail.item }} - {{ saledetail.quantity}} - {{ saledetail.price }} - {{ saledetail.amount }}</li>
                            
                    {% endfor %}
                    </ul>
                </td>
                <td>{{ sale.total_amount}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

    </div>
</div>
{% endblock content %}

templates/dashboard/sale_report.html
{% extends "partials/base.html" %}
{% block title %}Sale Report{% endblock title %}
{% block content %}

        <div class="container mt-5 shadow">
            <h3 class="mt-5  mx-5">Sale Report Date wise</h3>
            <hr>
            <form method="POST" class="as-table mx-4 p-4" id="item-form">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class=" btn btn-outline-primary  "
                 value="Search">
                </form>
            <div class="container-fluid">
                <div class="row">
                     <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Sale ID</th>
                                <th>Invoice</th>
                                <th>Sale Date</th>
                                <th>Customer</th>
                                <th>Contact No</th>
                                 <th>Details</th> 
                                <th>Total Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sale in sbetween %}
                                <tr>
                                    <td>{{ sale.id }}</td>
                                    <td>{{ sale.invoice_no }}</td>
                                    <td>{{ sale.datetime }}</td>
                                    <td>{{ sale.customer }}</td>
                                    <td>{{ sale.contact_no }}</td>
                                     <td>
                                        <ul>
                                            <li class="text-block">   item   -   Quantity  -   Price - anount</li>
                                            {% for saledetail in sale.saledetail_set.all %}
                                                <li>{{ saledetail.item }} - {{ saledetail.quantity}} - {{ saledetail.price }} - {{ saledetail.amount }}</li>
                                                
                                        {% endfor %}
                                        </ul>
                                    </td> 
                                    <td>{{ sale.total_amount}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock content %}